name: build-docker-image

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'requirements.txt'
      - '!.github/**'
      - '!.gitignore'
      - '!.vscode/**'
      - '!.DS_Store'
      - '!readme.md'
      - '!buildscript.sh'
      - '!docker-compose-example.yml'
      - '!rainlevel.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          pytest test_riverlevel.py -v --cov=riverlevel --cov-report=term-missing

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: magammon/riverlevel:latest
